# Generated by Django 4.1.7 on 2023-06-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utulisateurs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vaccination",
            old_name="dose_administré",
            new_name="dose_administre",
        ),
    ]
