# Generated by Django 4.1.7 on 2023-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dose',
            old_name='durée',
            new_name='duree',
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='status',
            field=models.CharField(choices=[('en_attent', 'En_Attent'), ('valide', 'Valide'), ('abondant', 'Abondant')], default='en_attent', max_length=20),
        ),
    ]
