# Generated by Django 4.1.7 on 2023-03-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=32816575, max_length=10),
            preserve_default=False,
        ),
    ]
