# Generated by Django 4.1.7 on 2023-05-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatvaccination',
            name='doses',
        ),
        migrations.DeleteModel(
            name='Vaccin_Dose',
        ),
    ]
