# Generated by Django 4.1.7 on 2023-03-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='nni',
            field=models.CharField(default=1111111111, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('directeur', 'Directeur'), ('responsable', 'Responsable'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
