# Generated by Django 4.1.7 on 2023-06-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0002_rename_durée_dose_duree_alter_vaccination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('responsable-center', 'Responsable-Center'), ('patient', 'Patient'), ('professionnel', 'Professionnel'), ('gerent-stock', 'Gerent-Stock')], default='patient', max_length=20),
        ),
        migrations.CreateModel(
            name='ProchaineDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vaccination', models.DateField()),
                ('nombre_doses', models.IntegerField(default=2)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.patient')),
                ('vaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.vaccine')),
            ],
        ),
    ]
