# Generated by Django 4.1.7 on 2023-05-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0003_vaccin_dose_certificatvaccination_doses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatvaccination',
            name='doses',
        ),
        migrations.DeleteModel(
            name='Vaccin_Dose',
        ),
    ]
