# Generated by Django 4.1.7 on 2023-06-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0003_alter_user_role_prochainedose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='duree',
            field=models.IntegerField(),
        ),
    ]
