# Generated by Django 4.1.7 on 2023-03-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0003_alter_user_managers_remove_user_username_user_nni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
