# Generated by Django 4.1.7 on 2023-03-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0004_remove_user_phone_number_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.6844704432229664, max_length=20, unique=True),
        ),
    ]
