# Generated by Django 4.1.7 on 2023-05-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0005_vaccin_dose_certificatvaccination_doses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatvaccination',
            name='doses',
        ),
    ]
