# Generated by Django 4.1.7 on 2023-05-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0006_remove_certificatvaccination_doses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificatVaccination',
        ),
    ]
