# Generated by Django 4.1.7 on 2023-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0006_alter_user_nni_wilaya_moughataa_centredevaccination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincenter',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('professionnel', 'Professionnel'), ('gerent-stock', 'Gerent-Stock')], default='admin', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.607041007235193, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('directeur-regional', 'Directeur-Regional'), ('responsable-center', 'Responsable-Center'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
