# Generated by Django 4.1.7 on 2023-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0007_admincenter_type_alter_user_nni_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('categorie', models.CharField(choices=[('enfants', 'Enfants'), ('jeunes-femmes', 'Jeunes-Femmes'), ('jeunes-hommes', 'Jeunes-Hommes'), ('veux', 'Veux')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.5086731145070067, max_length=20),
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doses', models.ManyToManyField(related_name='vaccines', to='utulisateurs.dose')),
            ],
        ),
    ]
