# Generated by Django 4.1.7 on 2023-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0008_dose_typevaccination_alter_user_nni_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.472037552959375, max_length=20),
        ),
    ]
