# Generated by Django 4.1.7 on 2023-05-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0008_certificatvaccination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wilaya',
            name='user',
        ),
        migrations.DeleteModel(
            name='CertificatVaccination',
        ),
    ]
