# Generated by Django 4.1.7 on 2023-05-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0009_remove_wilaya_user_delete_certificatvaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_certificat', models.CharField(max_length=10, unique=True)),
                ('date_delivration', models.DateField()),
                ('valide', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='vaccination_qr_codes/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.patient')),
                ('vaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.vaccine')),
            ],
        ),
    ]
