# Generated by Django 4.1.7 on 2023-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0010_certificatvaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilaya',
            name='code',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
