# Generated by Django 4.1.7 on 2023-04-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0011_remove_vaccine_doses_alter_user_nni_delete_dose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_doses', models.IntegerField(default=1)),
                ('duration_between_doses', models.DurationField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.07165002753340288, max_length=20),
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.vaccine')),
            ],
        ),
    ]
