# Generated by Django 4.1.7 on 2023-06-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0012_remove_vaccine_type_delete_typevaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('sexe_cible', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='femme', max_length=10)),
                ('age_minimum', models.IntegerField(default=1)),
                ('age_maximum', models.IntegerField(default=100)),
            ],
        ),
    ]
