# Generated by Django 4.1.7 on 2023-04-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0013_alter_user_nni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.9867836877645656, max_length=20),
        ),
        migrations.DeleteModel(
            name='Dose',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
