# Generated by Django 4.1.7 on 2023-04-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0015_vaccine_alter_user_nni_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.15951201006043358, max_length=20),
        ),
    ]
