# Generated by Django 4.1.7 on 2023-04-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0016_alter_user_nni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.4716163260232875, max_length=20),
        ),
    ]
