# Generated by Django 4.1.7 on 2023-04-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0017_alter_user_nni'),
    ]

    operations = [
        migrations.AddField(
            model_name='dose',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.9211381185470705, max_length=20),
        ),
    ]
