# Generated by Django 4.1.7 on 2023-04-03 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0020_alter_user_nni_vaccine_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.07070420143358758, max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.typevaccination'),
        ),
    ]
