# Generated by Django 4.1.7 on 2023-04-05 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0021_alter_user_nni_alter_vaccine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typevaccination',
            name='categorie',
            field=models.CharField(choices=[('enfants', 'Enfants'), ('jeunes-femmes', 'Jeunes-Femmes'), ('jeunes-hommes', 'Jeunes-Hommes'), ('veux', 'Veux'), ('tout-monde', 'Tout-Monde')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.47830275615171625, max_length=20),
        ),
        migrations.CreateModel(
            name='StockVaccins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOperation', models.CharField(choices=[('AJOUTER', 'Addition'), ('SUPRIMER', 'Suppresion')], max_length=15)),
                ('quantity', models.PositiveIntegerField()),
                ('dateExpiration', models.DateField()),
                ('dateOperation', models.DateTimeField(auto_now_add=True)),
                ('centerVaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.centredevaccination')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOperation', models.CharField(choices=[('AJOUTER', 'Addition'), ('SUPRIMER', 'Suppresion')], max_length=15)),
                ('quantite', models.PositiveIntegerField()),
                ('dateExpiration', models.DateField()),
                ('dateOperation', models.DateTimeField(auto_now_add=True)),
                ('centerVaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.centredevaccination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.vaccine')),
            ],
        ),
    ]
