# Generated by Django 4.1.7 on 2023-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0022_alter_typevaccination_categorie_alter_user_nni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.5330711538808642, max_length=20),
        ),
    ]
