# Generated by Django 4.1.7 on 2023-04-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0023_alter_user_nni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockvaccins',
            old_name='quantity',
            new_name='quantite',
        ),
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.968631255275414, max_length=20),
        ),
    ]
