# Generated by Django 4.1.7 on 2023-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0025_rename_user_historiquestock_createur_alter_user_nni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquestock',
            name='createur',
        ),
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.3927121043390488, max_length=20),
        ),
    ]
