# Generated by Django 4.1.7 on 2023-04-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0028_patient_alter_user_nni_alter_user_role_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nni',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.062081265703821775, max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='status',
            field=models.CharField(choices=[('en_attendant', 'En_Attendant'), ('validé', 'Validé'), ('abondant', 'Abondant')], default='en_attendant', max_length=20),
        ),
    ]
