# Generated by Django 4.1.7 on 2023-04-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0031_rename_centre_vaccination_center_alter_user_nni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.9874923501570599, max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='status',
            field=models.CharField(choices=[('en_attend', 'En_Attend'), ('validé', 'Validé'), ('abondant', 'Abondant')], default='en_attend', max_length=20),
        ),
    ]
