# Generated by Django 4.1.7 on 2023-04-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0032_alter_user_nni_alter_vaccination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincenter',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.centredevaccination'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nni',
            field=models.CharField(default=0.4943055290405344, max_length=20),
        ),
    ]
