# Generated by Django 4.1.7 on 2023-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0035_alter_centredevaccination_moughataa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquestock',
            name='typeOperation',
            field=models.CharField(max_length=15),
        ),
    ]
