# Generated by Django 4.1.7 on 2023-05-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utulisateurs', '0036_alter_historiquestock_typeoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquestock',
            name='numeroLot',
            field=models.CharField(default='I18207', max_length=50),
        ),
        migrations.AddField(
            model_name='stockvaccins',
            name='numeroLot',
            field=models.CharField(default='I18207', max_length=50),
        ),
        migrations.CreateModel(
            name='Vaccin_Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dose', models.DateField()),
                ('numeroDose', models.IntegerField()),
                ('numeroLot', models.CharField(max_length=50)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.centredevaccination')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.vaccination')),
                ('vaccins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulisateurs.vaccine')),
            ],
        ),
    ]
